OBJS = main.o \
collision.o config.o fightscreen.o fightui.o gamelogic.o \
mugenassignment.o \
mugenassignmentevaluator.o mugencommandhandler.o mugencommandreader.o \
mugenexplod.o mugensound.o \
mugenanimationhandler.o \
mugenstagehandler.o mugenstatecontrollers.o mugenstatehandler.o \
mugenstatereader.o pausecontrollers.o playerdefinition.o \
playerhitdata.o stage.o warningscreen.o titlescreen.o menuscreen.o \
projectile.o storyscreen.o story.o twoplayerselectscreen.o \
gameoverscreen.o ai.o
